import { Product } from "@/types/tProduct";

export const products: Product[] = [
  // naked model start
  {
    name: "500r",
    main_image: "/product/naked/500r/banner500r.png",
    model: "NAKED R",
    prix_mois: "?",
    location: "?",
    location_date_debut: "?",
    location_date_fin: "?",
    description:
      "La Voge 500 R est le roadster sportif de la marque. Son moteur bicylindre de 500 cm3 développe 47 chevaux. Une puissance idéale permettant aux jeunes permis A2 de profiter pleinement des capacités du véhicule. Coupleux à bas régime et vif à haut régime, ce bicylindre vous offrira des sensations uniques.Pour la partie cycle, Voge a équipé la 500 R d’un cadre périmétrique à simple berceau ouvert où le moteur bicylindre en ligne en devient une partie structurelle. Voge a également équipé ce véhicule de double freins à disque à l'avant et d'un disque simple à l’arrière. Combiné au système ABS, cette moto garantie une sécurité optimale à son pilote, en toutes circonstance. Enfin, les pneus Pirelli équipant la 500 R permettent de garder un grip parfait, sur tous types de routes.",
    tarifTTC: "75,000",
    serie: "?",
    serie_desc: "?",
    weight: "195",
    dimension: "2110 x 785 x ?",
    moteur: "Bicylindre 4T refroidissement liquide",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "34,5kW (47 chevaux) à 8500 tour/minute",
    couple_max: "25 Nm / 7000tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disque 300 mm",
    frain_arriere: "1 disque 245 mm",
    pneu_avant: "110/80 x 19",
    pneu_arriere: "150/70 x 17",
    volume_reservoir: "17,2 L",
    couleur: "Noir,Silver",
    gallery: [
      "/product/naked/500r/gallery1.jpeg",
      "/product/naked/500r/gallery2.jpeg",
      "/product/naked/500r/gallery3.jpeg",
      "/product/naked/500r/gallery4.jpeg",
      "/product/naked/500r/gallery5.jpeg",
      "/product/naked/500r/gallery6.jpeg",
    ],
    swiper: [
      "/product/naked/500r/backLeft.jpeg",
      "/product/naked/500r/backRight.jpeg",
      "/product/naked/500r/back.jpeg",
      "/product/naked/500r/front.jpeg",
      "/product/naked/500r/frontSide.jpeg",
      "/product/naked/500r/left-front.jpeg",
      "/product/naked/500r/sideL.jpeg",
      "/product/naked/500r/sideR.jpeg",
    ],
    mesure: "",
  },
  {
    name: "300r",
    main_image: "/product/naked/300R/banner300r.png",
    model: "NAKED R",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "5 965,00",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "195",
    dimension: "2215 x 840 x 1365",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW / 8500tr/mn",
    couple_max: "25 Nm / 7000tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques",
    frain_arriere: "1 disques",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/naked/300r/gallery1.png",
      "/product/naked/300r/gallery3.png",
    ],
    swiper: [
      "/product/naked/300r/front.jpeg",
      "/product/naked/300r/left.jpeg",
      "/product/naked/300r/frontside.jpeg",
      "/product/naked/300r/back.jpeg",
      "/product/naked/300r/sideR.jpeg",
    ],
  },
  {
    name: "525r",
    main_image: "/product/naked/525r/banner525r.png",
    model: "NAKED R",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "5 965,00",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "188",
    dimension: "2100 x 760 x 1170",
    moteur: "Bicylindre en ligne 4T",
    cylindre: "494",
    alesage: "47,5 ch à 8500 tr/min",
    taux_deC: "",
    puissance_max: " ",
    couple_max: "44.5 Nm / 7000 tour/minute",
    demarreur: "electrique",
    injection: "",
    boite_vitesse: "6 vitesses",
    transmission_finale: "",
    frain_avant: "2 disques 290 mm",
    frain_arriere: "1 disques 240 mm",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "17,2 litres",
    couleur: "Noir",
    gallery: [
      "/product/naked/525r/gallery.jpeg",
      "/product/naked/525r/gallery1.jpeg",
      "/product/naked/525r/gallery2.jpeg",
      "/product/naked/525r/gallery3.jpeg",
      "/product/naked/525r/gallery4.jpeg",
      "/product/naked/525r/gallery5.jpeg",
      "/product/naked/525r/gallery6.jpeg",
    ],
    swiper: [
      "/product/naked/525r/front.jpg",
      "/product/naked/525r/frontSide2.jpg",
      "/product/naked/525r/frontSide3.jpg",
      "/product/naked/525r/sideL.jpg",
    ],
  },
  // naked model end
  // classic model start
  {
    name: "300ac",
    main_image: "/product/classic/300AC/banner300ac.png",
    model: "Classic AC",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "47 900",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "150",
    dimension: "2025 x 795 x ?",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW (26 chevaux) / 8500 tour/minute",
    couple_max: "25 Nm / 7000 tour/minute",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques 300 mm",
    frain_arriere: "1 disques 220 mm",
    pneu_avant: "110/70 x 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/classic/300ac/gallery2.png",
      "/product/classic/300ac/gallery4.png",
      "/product/classic/300ac/gallery5.png",
      "/product/classic/300ac/gallery6.png",
    ],
    swiper: [
      "/product/classic/300ac/front.jpeg",
      "/product/classic/300ac/back.jpeg",
      "/product/classic/300ac/frontside.jpeg",
      "/product/classic/300ac/sideR.jpeg",
      "/product/classic/300ac/sideL.jpeg",
    ],
  },
  {
    name: "300acx",
    main_image: "/product/classic/300acx/banner300acx.png",
    model: "Classic AC",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "49 500",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "150",
    dimension: "2050 x 780 x ?",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "300",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW (26 chevaux) / 8500 tour/minute",
    couple_max: "25 Nm / 7000 tour/minute",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques 300 mm",
    frain_arriere: "1 disques 220 mm",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "15 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/classic/300acx/gallery1.jpeg",
      "/product/classic/300acx/gallery2.jpeg",
      "/product/classic/300acx/gallery3.jpeg",
      "/product/classic/300acx/gallery4.jpeg",
      "/product/classic/300acx/gallery5.jpeg",
      "/product/classic/300acx/gallery6.jpeg",
    ],
    swiper: [
      "/product/classic/300acx/front.jpeg",
      "/product/classic/300acx/back.jpeg",
      "/product/classic/300acx/backleft.jpeg",
      "/product/classic/300acx/backright.jpeg",
      "/product/classic/300acx/frontside.jpeg",
      "/product/classic/300acx/frontside2.jpeg",
      "/product/classic/300acx/sideR.jpeg",
      "/product/classic/300acx/sideL.jpeg",
    ],
  },
  {
    name: "500ac",
    main_image: "/product/classic/500AC/banner500ac.png",
    model: "Classic AC",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "79 900",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "195",
    dimension: "2100 x 795 x ?",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "471",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "34,5kW (47 chevaux) / 8500 tour/minute",
    couple_max: "42,5 Nm / 7000 tour/minute",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques",
    frain_arriere: "1 disques",
    pneu_avant: "110/70 x 17",
    pneu_arriere: "160/60 x 17",
    volume_reservoir: "19 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/classic/500AC/gallery1.jpeg",
      "/product/classic/500AC/gallery2.jpeg",
      "/product/classic/500AC/gallery3.jpeg",
      "/product/classic/500AC/gallery4.jpeg",
      "/product/classic/500AC/gallery5.jpeg",
      "/product/classic/500AC/gallery6.jpeg",
    ],
    swiper: [
      "/product/classic/500AC/front.jpeg",
      "/product/classic/500AC/frontleft.jpeg",
      "/product/classic/500AC/front.jpeg",
      "/product/classic/500AC/back.jpeg",
      "/product/classic/500AC/backleft.jpeg",
      "/product/classic/500AC/backright.jpeg",
      "/product/classic/500AC/frontside.jpeg",
      "/product/classic/500AC/sideR.jpeg",
      "/product/classic/500AC/sideL.jpeg",
    ],
  },
  // classic model end
  // trail model start
  {
    name: "525dsx",
    main_image: "/product/trail/525dsx/banner525dsx.png",
    model: "Trail DS",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "5 965,00",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "195",
    dimension: "2215 x 840 x 1365",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW / 8500tr/mn",
    couple_max: "25 Nm / 7000tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques",
    frain_arriere: "1 disques",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/trail/525dsx/gallery1.jpeg",
      "/product/trail/525dsx/gallery2.jpeg",
      "/product/trail/525dsx/gallery3.jpeg",
      "/product/trail/525dsx/gallery4.jpeg",
      "/product/trail/525dsx/gallery5.jpeg",
      "/product/trail/525dsx/gallery6.jpeg",
    ],
    swiper: [
      "/product/trail/525dsx/front.jpeg",
      "/product/trail/525dsx/frontside.jpeg",
      "/product/trail/525dsx/frontside2.jpeg",
      "/product/trail/525dsx/back.jpeg",
      "/product/trail/525dsx/backside.jpeg",
      "/product/trail/525dsx/backside2.jpeg",
      "/product/trail/525dsx/sideR.jpeg",
      "/product/trail/525dsx/sideL.jpeg",
    ],
  },
  {
    name: "650dsx",
    main_image: "/product/trail/650dsx/banner650DSX.png",
    model: "Trail DS",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "99 000",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "170",
    dimension: "2155 x 850 x 1390",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d’équilibrage intérieur permettant de très faible vibration.",
    cylindre: "651",
    alesage: "100 x 83",
    taux_deC: "100 x 83",
    puissance_max: "35 kW / 6750 tr/mn",
    couple_max: "60 Nm / 5500 tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques 298 mm",
    frain_arriere: "1 disques 240 mm",
    pneu_avant: "110/80 - 19",
    pneu_arriere: "150/70 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/trail/650dsx/gallery1.jpeg",
      "/product/trail/650dsx/gallery3.jpeg",
      "/product/trail/650dsx/gallery4.jpeg",
    ],
    swiper: [
      "/product/trail/650dsx/front.jpeg",
      "/product/trail/650dsx/frontside.jpeg",
      "/product/trail/650dsx/frontside2.jpeg",
      "/product/trail/650dsx/back.jpeg",
      "/product/trail/650dsx/backside.jpeg",
      "/product/trail/650dsx/backside2.jpeg",
      "/product/trail/650dsx/sideR.jpeg",
      "/product/trail/650dsx/sideL.jpeg",
    ],
  },
  {
    name: "300ds",
    main_image: "/product/trail/300ds/banner300ds.png",
    model: "Trail DS",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "44 900",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "195",
    dimension: "2215 x 840 x 1365",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW / 8500tr/mn",
    couple_max: "25 Nm / 7000tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques",
    frain_arriere: "1 disques",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/trail/300ds/gallery.jpeg",
      "/product/trail/300ds/gallery2.jpeg",
      "/product/trail/300ds/gallery3.jpeg",
      "/product/trail/300ds/gallery4.jpeg",
      "/product/trail/300ds/gallery5.jpeg",
    ],
    swiper: [
      "/product/trail/300ds/front.jpeg",
      "/product/trail/300ds/frontside.jpeg",
      "/product/trail/300ds/frontside2.jpeg",
      "/product/trail/300ds/backside.jpeg",
      "/product/trail/300ds/sideR.jpeg",
    ],
  },
  {
    name: "650ds",
    main_image: "/product/trail/650ds/banner650ds.png",
    model: "Trail DS",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "5 965,00",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "195",
    dimension: "2215 x 840 x 1365",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW / 8500tr/mn",
    couple_max: "25 Nm / 7000tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques",
    frain_arriere: "1 disques",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/trail/650ds/gallery8.webp",
      "/product/trail/650ds/gallery9.webp",
      "/product/trail/650ds/gallery10.webp",
      "/product/trail/650ds/gallery11.webp",
      "/product/trail/650ds/gallery12.webp",
      "/product/trail/650ds/gallery.jpeg",
      "/product/trail/650ds/gallery3.jpeg",
      "/product/trail/650ds/gallery4.jpeg",
      "/product/trail/650ds/gallery5.jpeg",
      "/product/trail/650ds/gallery6.jpeg",
      "/product/trail/650ds/gallery7.jpeg",
    ],
    swiper: [
      "/product/trail/650ds/front.png",
      "/product/trail/650ds/frontside.png",
      "/product/trail/650ds/frontside2.png",
      "/product/trail/650ds/backside.png",
      "/product/trail/650ds/sidR.png",
    ],
  },

  {
    name: "300rally",
    main_image: "/product/trail/300rally/banner300rally.png",
    model: "Trail DS",
    prix_mois: "64,66",
    location: "850,00",
    location_date_debut: "13/03/2023",
    location_date_fin: "13/05/2023",
    description:
      "Une moto pensée pour les nouveaux accédants au permis A2 et pour ceux désirant revenir à la moto sans se faire peur. La 300 R est la moto idéale pour bien commencer dans le monde du deux roues motorisé. Une moto facile, légère, à la tenue de route parfaite sans oublier pour le pilote et le ou la passagère un confort extraordinaire par les choix subtils des suspensions. Le plaisir de rouler…",
    tarifTTC: "5 965,00",
    serie: "STREET SERIE",
    serie_desc:
      "La Street Série 300 R a été pensé autour d'un cadre tubulaire et d'un bras oscillant a symétrique. Cette association est le cœur même de l'homogénéité maximale de cette moto. Son moteur 300cc à double arbre à came en tête et son refroidissement liquide lui confère une onctuosité et une résistance supérieure. Sa boîte 6 vitesses permet à tous les nouveaux conducteur une meilleure gestion des montés en régime du moteur. Comme la 500 R, La 300 AC et la 300RR, elle dispose de jantes en alliage, de pneus sans chambre, d'un phare à LED ainsi que le feu arrière, de clignotants à LED et d'un compteur digital, numérique aux multiples informations.",
    weight: "195",
    dimension: "2215 x 840 x 1365",
    moteur:
      "Mono-cylindre, 4 temps, 4 soupapes, DOHC, refroidissement liquide, axe d'équilibrage intérieur permettant de très faible vibration.",
    cylindre: "292.4",
    alesage: "78x61.2",
    taux_deC: "11:1",
    puissance_max: "19kW / 8500tr/mn",
    couple_max: "25 Nm / 7000tr/mn",
    demarreur: "electrique",
    injection: "CDI",
    boite_vitesse: "6 vitesses",
    transmission_finale: "Chaine",
    frain_avant: "2 disques",
    frain_arriere: "1 disques",
    pneu_avant: "110/70 - 17",
    pneu_arriere: "150/60 - 17",
    volume_reservoir: "16 litres",
    couleur: "Noir,Silver",
    gallery: [
      "/product/trail/300rally/gallery.jpeg",
      "/product/trail/300rally/gallery1.jpeg",
      "/product/trail/300rally/gallery2.jpeg",
      "/product/trail/300rally/gallery3.jpeg",
      "/product/trail/300rally/gallery4.jpeg",
      "/product/trail/300rally/gallery5.jpeg",
    ],
    swiper: [
      "/product/trail/300rally/back.jpeg",
      "/product/trail/300rally/backside.jpeg",
      "/product/trail/300rally/backside1.jpeg",
      "/product/trail/300rally/sider.jpeg",
      "/product/trail/300rally/sidel.jpeg",
    ],
  },
];

export const truncate = (input: string) =>
  input?.length > 300 ? `${input.substring(0, 350)}...` : input;
