import Head from "next/head";
import Navbar from "@/layout/Navbar";
import "./globals.css";
import { Roboto_Condensed } from "next/font/google";
import Footer from "@/layout/Footer";

const roboto = Roboto_Condensed({ subsets: ["latin"], weight: "400" });

export default function RootLayout({
  children,
  title = "voge",
  description = "Generated by create next app",
}: {
  children: React.ReactNode;
  title?: string; // Optional title prop
  description?: string; // Optional description prop
}) {
  return (
    <html lang="en">
      <Head>
        {/* Set the title and description dynamically */}
        <title>{title}</title>
        <meta name="description" content={description} />
      </Head>
      <body className={roboto.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
